use_frameworks!

#source 'https://github.com/truongtvd/PhotoEditorSDK.git'
target 'SMPhotoEditorSDK_Example' do
    
#  pod 'SMPhotoEditorSDK', :path => '../'
pod 'SMPhotoEditorSDK'

  target 'SMPhotoEditorSDK_Tests' do
    inherit! :search_paths

    
  end
end
